spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    aws:
      credentials:
        access-key: ${BUCKET_ACCESS_KEY}
        secret-key: ${BUCKET_SECRET_KEY}
      s3:
        bucket: ${BUCKET_NAME}
      region:
        static: ${BUCKET_REGION}

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

springdoc:
  swagger-ui:
    path: /api-test
  paths-to-match: /api/v1/**

jwt:
  secret: ${JWT_SECRET}